runtime: python27
api_version: 1
threadsafe: true

instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 10m


libraries:
- name: pycrypto
  version: 2.6.1

handlers:
- url: /.*
  script: main.app
